apiVersion: v1
kind: Namespace
metadata:
  name: my-application-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  namespace: my-application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application-server
          image: 131924/my-application:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
  namespace: my-application-ns
spec:
  selector:
    app: my-application
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31163
      protocol: TCP

