apiVersion: v1
kind: Namespace
metadata:
  name: my-application-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  namespace: my-application-ns
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application 
    spec:
      containers:
      - name: my-application-server
        image: 131924/my-application:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
  namespace: my-application-ns
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 3000
      nodePort: 31500  # Pick a port in range 30000–32767
